#!/usr/bin/env python3
import requests
import sys

def factor(n):
    url = f"http://factordb.com/api?query={n}"
    res = requests.get(url).json()
    return res

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <number>")
        sys.exit(1)

    n = sys.argv[1]
    res = factor(n)

    print(f"[+] Query: {n}")
    print("[+] Status:", res.get("status", ""))
    print("[+] Factors:")
    for f, exp in res["factors"]:
        print(f"   {f}^{exp}")
