

# This file was *autogenerated* from the file decode.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_61 = Integer(61); _sage_const_2081 = Integer(2081); _sage_const_4177 = Integer(4177)
def S(a):
    return {
        p for p in range(_sage_const_3 , _sage_const_4 *a + _sage_const_1 , _sage_const_2 )
        if kronecker_symbol(a, p) == -_sage_const_1 
    }

def strong_pseudoprime(A, ks):
    x = var('x')
    def f(i):
        p = product(ks[j]*(x-_sage_const_1 )+_sage_const_1  for j in range(len(ks)) if j != i)
        return (p - _sage_const_1 ) / (x - _sage_const_1 )

    # subsets is dict that maps bases a_i to subsets of residues mod 4a
    subsets = {}
    for a in A:
        subsets[a] = list(set.intersection(*(
            {(pow(k, -_sage_const_1 , _sage_const_4 *a) * (s + k - _sage_const_1 )) % (_sage_const_4 *a) for s in S(a)}
            for k in ks
        )))

    indices = [_sage_const_0 ] * len(subsets)
    def bruteforce(i, r, m):
        if i == len(indices):
            yield find_pseudoprime(r, m)
            return

        for residue in subsets[A[i]]:
            try:
                r = crt([r, residue], [m, A[i] * _sage_const_4 ])
            except ValueError:
                continue
            yield from bruteforce(i + _sage_const_1 , r, lcm(m, A[i] * _sage_const_4 ))

    def find_pseudoprime(r, m):
        i = _sage_const_0 
        while True:
            p1 = m*i + r
            ps = [p1] + [
                k*(p1 - _sage_const_1 ) + _sage_const_1 
                for k in ks[_sage_const_1 :]
            ]
            if all(is_prime(p) for p in ps):
                return ps
            i += _sage_const_1 

    # initial congruences to ensure m_i is integer
    rs, ms = [], []
    for i in range(_sage_const_1 , len(ks)):
        sol, = solve_mod(f(i).full_simplify(), ks[i])[_sage_const_0 ]
        rs.append(int(sol)); ms.append(ks[i])

    yield from bruteforce(_sage_const_0 , crt(rs, ms), lcm(ms))

# USAGE
A = prime_range(_sage_const_2 , _sage_const_61 +_sage_const_1 )
for p in strong_pseudoprime(A, [_sage_const_1 , _sage_const_2081 , _sage_const_4177 ]):
    # assert miller_rabin(product(p), A)
    print(p)

